import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillTwitterCircle,
  AiFillYoutube,
} from "react-icons/ai";
import Head from "next/head";
import Image from "next/image";

import Dev from "../assets/sun-boat.jpg";

const Home = () => {
  return (
    <div>
      <Head>
        <title>React Sample Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-kalam">Developed by Nidheesh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white text-2xl rounded-md ml-4"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Developer Name
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Developer and Learner</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin className="hover:text-pink-600" />
            <AiFillYoutube className="hover:text-pink-600" />
            <AiFillTwitterCircle className="hover:text-pink-600" />
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96">
            <Image src={Dev} alt="dev" layout="fill" objectFit="cover" />
            {/* // layout="fill" */}
          </div>
        </section>
        <section>
          <div className="py-4">
            <h3 className="text-3xl py-1">Services I offer </h3>
            <p className="text-md py-2 leading-08 text-gray-80">
              Since the beginning of the journey as a freelance developer, I've
              done remote work for
              <span className="text-teal-500">agencies</span>
              and collaborated with talented to create digit for both business
              and customer use.
            </p>
            <p className="text-md py-2 leading-08 text-gray-80">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit
              inventore saepe porro repellendus optio quos pariatur expedita ab
              cupiditate nihil culpa asperiores facilis, recusandae tenetur, cum
              adipisci soluta sequi. Laudantium!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center p-10 shadow-lg rounded-xl my-10">
              <Image src={Dev} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam
                hic vel ea id fuga cumque blanditiis maiores minus illum
                reprehenderit.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="py-1 text-gray-800">Figma</p>
              <p className="py-1 text-gray-800">Illustrator</p>
              <p className="py-1 text-gray-800">Photoshop</p>
            </div>

            <div className="text-center p-10 shadow-lg rounded-xl my-10">
              <Image src={Dev} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Cupiditate reiciendis dicta impedit, consectetur qui id deleniti
                nobis recusandae? Consequatur, quaerat.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I used:</h4>
              <p className="py-1 text-teal-800">Figma</p>
              <p className="py-1 text-teal-800">Illustrator</p>
              <p className="py-1 text-teal-800">Photoshop</p>
            </div>
            <div className="text-center p-10 shadow-lg rounded-xl my-10">
              <Image src={Dev} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful sites</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum
                placeat consectetur iusto reiciendis.
              </p>
              <h4 className="py-4 text-teal 600">Sites I developed</h4>
              <p className="py-1 text-teal-800">Sample site 1</p>
              <p className="py-1 text-teal-800">Sample site 2</p>
              <p className="py-1 text-teal-800">Sample site 3</p>
            </div>
          </div>
        </section>
        <section>
          <div className="md:max-w-lg mx-auto">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-08 text-gray-80">
              Since the beginning of the journey as a freelance developer, I've
              done remote work for
              <span className="text-teal-500">agencies</span>
              and collaborated with talented to create digit for both business
              and customer use.
            </p>
            <p className="text-md py-2 leading-08 text-gray-80">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit
              inventore saepe porro repellendus optio quos pariatur expedita ab
              cupiditate nihil culpa asperiores facilis, recusandae tenetur, cum
              adipisci soluta sequi. Laudantium!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg-flex-row lg:flex-wrap">
            <div className="basis-1/2 flex-1">
              <Image
                src={Dev}
                alt="webImages"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={Dev}
                alt="webImages"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={Dev}
                alt="webImages"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={Dev}
                alt="webImages"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
