import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Sample Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-blue-700 min-h-screen w-screen p-4">hello</section>
      </main>
    </div>
  );
}
